# Generated by Django 3.2.7 on 2021-09-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=30)),
                ('field1', models.FloatField(max_length=10)),
                ('field2', models.FloatField(max_length=10)),
                ('field3', models.FloatField(max_length=10)),
                ('field4', models.FloatField(max_length=10)),
                ('field5', models.FloatField(max_length=10)),
                ('field6', models.FloatField(max_length=10)),
                ('field7', models.FloatField(max_length=10)),
                ('field8', models.FloatField(max_length=10)),
            ],
        ),
    ]
